cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run091
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run092
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run093
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run094
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run095
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run096
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run097
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run098
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run099
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run100
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run101
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run102
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run103
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run104
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run105
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run106
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run107
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run108
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run109
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run110
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run111
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run112
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run113
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run114
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run115
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run116
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run117
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run118
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run119
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run120
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run121
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run122
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run123
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run124
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run125
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run126
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run127
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run128
sbatch cuda_job_script_wilkes
cd /rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsL/run129
sbatch cuda_job_script_wilkes
