cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run018
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run019
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run020
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run021
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run022
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run023
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run024
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run025
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run026
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run027
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run028
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run029
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run030
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run031
sbatch cuda_job_script_tursa
cd /mnt/lustre/tursafs1/home/dp153/dp153/shared/lfi_project/runsL/run032
sbatch cuda_job_script_tursa
