#!/bin/tcsh

#SBATCH --partition CORES16
#SBATCH -N1
#SBATCH -n12
#SBATCH --mail-user=lorne.whiteway@star.ucl.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --job-name=pkdgrav3
#SBATCH --time=18:00:00
#SBATCH --mem=96000

source /share/splinter/ucapwhi/lfi_project/set_environment.csh USE
cd /share/splinter/ucapwhi/lfi_project/experiments/computenode_512_256_1000

mpirun /share/splinter/ucapwhi/lfi_project/pkdgrav3/build_cores16/pkdgrav3 ./control.par > ./example_output.txt

