#!/bin/tcsh

#SBATCH -N1
#SBATCH -n1
#SBATCH --mail-user=lorne.whiteway@star.ucl.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --job-name=monitor
#SBATCH --time=2-00:00:00
#SBATCH --mem=12000
#SBATCH --output=/share/splinter/ucapwhi/lfi_project/experiments/v100_1024_4096_1070/monitor_output.txt


source /share/splinter/ucapwhi/lfi_project/set_environment.csh USE
cd /share/splinter/ucapwhi/lfi_project/experiments/v100_1024_4096_1070/

/share/splinter/ucapwhi/lfi_project/scripts/monitor.py /share/splinter/ucapwhi/lfi_project/experiments/v100_1024_4096_1070/ True 600


