#!/bin/bash

# Based on information at https://epcced.github.io/dirac-docs/tursa-user-guide/scheduler/

# Slurm job options
#SBATCH --job-name=pkdgrav3
#SBATCH --time=36:00:00
#SBATCH --account=DP327
#SBATCH --mail-user=lorne.whiteway@star.ucl.ac.uk
#SBATCH --mail-type=FAIL
#SBATCH --export=none


#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=48
#SBATCH --partition=gpu-a100-80
#SBATCH --qos=standard
#SBATCH --gres=gpu:1
#SBATCH --mem=30000
#SBATCH --hint=multithread

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

source /mnt/lustre/tursafs1/home/dp327/dp327/shared/lfi_project/set_environment_tursa.sh USE

application="/rds/user/dc-whit2/rds-dirac-dp153/lfi_project/runsXXX/runXXX/pkdgrav3_and_post_process.sh"
options=""
CMD="$application $options"
eval $CMD

